<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>8600;8601;8618;8602;8603;8604;8625;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>../Build/ImGui/Debug/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>../Build/ImGui/Release/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prowl.Runtime\Prowl.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.90.8.1" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input.Extensions" Version="2.23.0" />
  </ItemGroup>

</Project>
