<Project Sdk="Microsoft.Build.NoTargets/3.7.134">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\**\*" Exclude="node_modules\**;build\**" />
    <None Include="src\**\*" />
    <None Include="static\**\*" />
    <None Include="docusaurus.config.js" />
    <None Include="package.json" />
    <None Include="sidebars.js" />
    <None Include="babel.config.js" />
    <None Include="start-docs.cmd" />
    <None Include=".gitignore" />
  </ItemGroup>
</Project>
